name: SignInPlus
main: cc.vastsea.SignInPlus
version: ${version}
api: spigot
api-version: '1.20'
authors:
  - Snowball_233
  - zrll_
description: >
  A modern, full-featured check-in system for Spigot servers: daily sign-ins, streak and total tracking, make-up cards, top rankings, points economy, PlaceholderAPI placeholders, optional Web API, and rich configurable rewards.
depend:
  - Kotlin
softdepend:
  - PlaceholderAPI
commands:
  signinplus:
    aliases: [sip, signin, checkin]
    description: Main command for SignInPlus
    usage: /signinplus help
permissions:
  signinplus.user:
    description: Can use sign-in features (default for players)
    default: true
  signinplus.make_up:
    description: Can use make-up sign (default for players)
    default: true
  signinplus.admin:
    description: Administer the sign-in system (force check-in, make-up for others, reload)
    default: op